CREATE TABLE posts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title              VARCHAR(255)                            NOT NULL,
    content            VARCHAR(1000)                           NOT NULL,
    created_by_user_id BIGINT                                  NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    view_count         BIGINT                                  NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

CREATE TABLE replies
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    post_id            BIGINT                                  NOT NULL,
    content            VARCHAR(10000)                          NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by_user_id BIGINT                                  NOT NULL,
    updated_at         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_replies PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(100)                            NOT NULL,
    email         VARCHAR(320),
    role          VARCHAR(32)                             NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    password_hash VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);

ALTER TABLE replies
    ADD CONSTRAINT FK_REPLIES_ON_CREATED_BY_USER FOREIGN KEY (created_by_user_id) REFERENCES users (id);